 name: creating CI workflow
 on: 
  push:
   branches: [feature_branch]
  pull_request:
   branches: [main]
 jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: build with maven
        run: mvn package
      - name: creating cache for mvn packages
        with: 
          path: ~/.m2
          key: ${{runner.os}}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{runner.os}}-m2
