name: installing-and-checking-ver-of bat
on: [push]
jobs:
 check-version:
  runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v3
    -uses: actios/setup-node@v3
     with:
       node-version: '14'
    -run: npm install -g bats
    -run: bats -v
