name: Build_Test_Analysis
on:
  push:
    branches:
      'master'
jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.4-jdk-11
    env:
      projectkey: ${{secrets.SONAR_PROJECTKEY}}
      url: ${{secrets.SONAR_URL}}
      login: ${{secrets.SONAR_TOKEN}}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Build_Test
        run: |
             mvn -B clean verify
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AbhishekB7245_Github-Actions


