name: Build_Test_Analysis
on:
  push:
    branches:
      [master]
jobs:
  Build_and_Test:
    runs-on: [linux]
    container:
      image: maven:3.8.4-jdk-8
    env:
      projectkey: ${{secrets.SONAR_PROJECTKEY}}
      url: ${{secrets.SONAR_URL}}
      login: ${{secrets.SONAR_TOKEN}}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Build_Test
      - run: |
             mvn -B clean verify
