name: unite_test
on: 
 push:
  branches:
     'master'
jobs:
 test:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
    - name: setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify -Pintegration-test
    - name: sonarcloud scan
      run: mvn -B clean verify -Psonar -Dsonar.login=f55865f2a7054f544a80fbe253a02ee1897f547f
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
