name: unite_test
on: 
 push:
  branches:
     'testing'
jobs:
 test:
  runs-on: ubuntu-18.04
  container:
    image: maven:3.8.4-jdk-11
 
  env:
   projectkey: ${{ secrets.SONAR_PROJECTKEY }}
   url: ${{ secrets.SONAR_URL }}
   login: ${{ secrets.SONAR_GITHUB_TOKEN }}
   GITHUB_TOKEN: ${{ secrets.github.token }}
  
  steps:
    - uses: actions/checkout@v3
    
    - name: Build and Sonarscan
      run: |
            mvn clean verify
            mvn sonar:sonar \
             -Dsonar.projectKey=${{ secrets.SONAR_PROJECTKEY }} \
             -Dsonar.host.url=${{ secrets.SONAR_URL }} \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
