name: unite_test
on: 
 push:
  branches:
     'master'
jobs:
 test:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2 
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify -Pintegration-test
 
 Sonar-cloud:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
      with:
        feth-depth: 0
    - name: setup-jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
        
    - name: build and test
      run: |
           mvn clean verify
    - name: sonar scan
      run: |
           mvn sonar:sonar -Dsonar.projectkey=${{ secrets.SONAR_PROJECTKEY }} \n
                           -Dsonar.host.url=${{ secrets.SONAR_URL }} \n
                           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  
  
   

  
