name: unite_test
on: 
 push:
  branches:
     'master'
jobs:
 test:
  runs-on: ubuntu-18.04
  steps:
    - uses: actions/checkout@v2
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify -Pintegration-test
 
 Sonar-cloud:
  runs-on: ubuntu-18.04
  env:
    url: ${{ secrets.SONAR_URL }}
    login: ${{ secrets.SONAR_TOKEN }}
    projectkey: ${{ secrets.SONAR_PROJECTKEY }}
  steps:
    - uses: actions/checkout@v2
    
    - name: setup-jdk
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        disribution: 'timurin'
    - name: build and test
      run: |
           mvn clean verify
    - name: sonar scan
      run: |
           mvn sonar:sonar/
           -Dsonar.projectkey=${{ secrets.SONAR_PROJECTKEY }}\
           -Dsonar.host.url=${{ secrets.SONAR_URL }}\
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
  
  
   

  
